### ISSUE TITLE
Most recent PR broke links

### ISSUE THREAD

**Issue by boba-and-beer** [tesseract-ocr/tessdoc#57] opened 2021-09-13 03:27 UTC
Hi - the most recent PR to Tessdocs broke a number of links in the documentation.

When we navigate to this page and click "User manual", we no longer get directed to the right page and returns an error.

https://tesseract-ocr.github.io/

Think this has something to do with Github Pages. 

(Not sure if this is the right place to report this issue but seems right).

**Comment by stweil** [comment] 2021-09-13 04:48
This should be fixed now. Please test and close the issue then.

The problem was caused by the renaming of the default branch from `master` to `main`. GitHub then rebuilds the GitHub pages. That took more time than expected.

**Comment by boba-and-beer** [comment] 2021-09-13 08:49
Yeah works now mate cheers

**Closed** 2021-09-13 08:49 UTC
